version: "2"

services:
  jenkins:
    image: jenkins
    ports:
      - "80:8080"
    networks:
      - front-tier
      - back-tier
  slave1:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/group:/etc/group
      - /home/ant_weiss/.docker:/home/jenkins/.docker
      - /usr/bin/kubectl:/usr/bin/kubectl
      - /home/ant_weiss/.kube:/home/jenkins/.kube
    image: otomato/jenkins-slave-alpine:curl
    networks:
      - front-tier
      - back-tier
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - front-tier
      - back-tier
networks:
  front-tier:
  back-tier:
